CREATE INDEX IF NOT EXISTS "funds_active_user_idx" ON "funds" USING btree ("user_id","id") WHERE "funds"."deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "funds_active_savings_idx" ON "funds" USING btree ("user_id","is_savings") WHERE "funds"."deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_active_page_idx" ON "transactions" USING btree ("user_id","occurred_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "transactions"."deleted_at" IS NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_events_page_idx" ON "transactions" USING btree ("user_id","occurred_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "transactions"."deleted_at" IS NULL AND "transactions"."parent_id" IS NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_pending_events_page_idx" ON "transactions" USING btree ("user_id","occurred_at" DESC NULLS LAST,"id" DESC NULLS LAST) WHERE "transactions"."deleted_at" IS NULL AND "transactions"."parent_id" IS NULL AND "transactions"."is_pending" = true;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_active_postings_wallet_idx" ON "transactions" USING btree ("user_id","wallet_id") WHERE "transactions"."deleted_at" IS NULL AND "transactions"."is_posting" = true AND "transactions"."wallet_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_active_postings_fund_idx" ON "transactions" USING btree ("user_id","fund_id") WHERE "transactions"."deleted_at" IS NULL AND "transactions"."is_posting" = true AND "transactions"."fund_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_active_children_idx" ON "transactions" USING btree ("user_id","parent_id","id" DESC NULLS LAST) WHERE "transactions"."deleted_at" IS NULL AND "transactions"."is_posting" = true AND "transactions"."parent_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "transactions_pending_by_user_idx" ON "transactions" USING btree ("user_id") WHERE "transactions"."deleted_at" IS NULL AND "transactions"."is_pending" = true;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wallets_active_user_idx" ON "wallets" USING btree ("user_id","id") WHERE "wallets"."deleted_at" IS NULL;